linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - deadcode
    - gosimple
    - structcheck
    - varcheck
    - typecheck
    - unused
    - misspell
    - gocyclo
    - gocognit
    - goconst
    - dupl
    - goimports
    - golint
    - gosec
    - prealloc
    - scopelint
    - unconvert
    - unparam
    - whitespace
    - gochecknoinits
    - gochecknoglobals
    - godox
    - goerr113
    - gomnd 
    - gomodguard
    - goprintffuncname
    - gosec
    - interfacer
    - lll
    - maligned
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - whitespace
